import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/nav/MainNav";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/themeProvider/theme-provider";

const font = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className}  antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainNav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
